server:
  port: 9000

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/

spring:
  application:
    name: Organisation-service


logging:
  level:
    com.codeusingjava: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,beans
    jmx:
      exposure:
        include: health,info,env,beans